### ISSUE TITLE
out of memory on 12g memory card

### ISSUE THREAD

**Issue by NHZlX** [shicai/MobileNet-Caffe#12]
i trained the model  on flowers 102 with input size 224 and batch size 50.  the graphics is k40 with 12g memory.  it's out of memory. What's the problem?

**Comment by shicai** [comment]
"please uncomment engine: CAFFE used in the conv layers with group, if you encounter memory problems."

**Comment by Satisfie** [comment]
But, when I use engine: CAFFE, it's real slow.  do you have this problem, i use 4 TitanXP

**Comment by NoRush-Android** [comment]
@shicai May i know what you meant by uncomment engine:CAFFE with group? Is it means that i need to delete the # sign and comment out/delete the group parameters?

**Comment by shicai** [comment]
@NoRush-Android yes, delete '#'.

**Comment by NoRush-Android** [comment]
Alright, thanks @shicai
