### ISSUE TITLE
caffe implementation speed

### ISSUE THREAD

**Issue by GragonShit** [shicai/MobileNet-Caffe#13]
I used your prototxt to train on dataset cifar10. I thought it must be very fast. But On P40 GPU, 32*32 input, 50 batchsize, it's 5+ second one batch. 
So, Something wrong happend when the model is only 13M?

**Comment by shicai** [comment]
caffe's depthwise convolution implemented by group is very slow.

**Comment by GragonShit** [comment]
@shicai 
when i train mobilenet, its convergence is very slow. can u release your train log?
Thx~~

**Comment by sudevbohra** [comment]
Does this mean using caffe's depthwise convolutions would also result in slower inference time? (assuming yes)

**Comment by cooliybob** [comment]
I have the same question as @sudevbohra .

**Comment by shicai** [comment]
As posted in https://github.com/shicai/MobileNet-Caffe/issues/8#issuecomment-304430118, depthwise conv in caffe is very slow.
Maybe a highly optimized CUDA implemenation of depthwise conv is needed for caffe.
Hope it will be supported by CuDNN in the next few months.

**Comment by NicolaiHarich** [comment]
[CuDNN 7](https://developer.nvidia.com/cudnn) supports now grouped convolutions! However I got a "CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR" for the last 3 dw-conv-layers so I had to use the CAFFE engine for those layers. I find this very strange.

With this setting I measured the time averaged over 100 iterations:
- Average Forward pass: 32.4181 ms
- Average Backward pass: 47.5687 ms.

which is slower than just using the CAFFE engine for all dw-convolutions (Average Forward pass: 21.6994 ms / Average Backward pass: 33.0519 ms).

What's your experience?

btw: my setting for this experiment: _cuda8, cudnn7, GeForce GTX 1080_

**Comment by shicai** [comment]
I have not updated it to cudnn7 yet.
I will check it later.

**Comment by lrjun6188** [comment]
@GragonShit  should we modify the caffe.proto file or other file before training the MobileNet

**Comment by twmht** [comment]
@shicai 

can you provide the baseline model (without depthwise and pointwise convolution)?

**Comment by sunjunlishi** [comment]
your profile  has no  DepthwiseConvolutionLayer

**Comment by sunjunlishi** [comment]
you  say: caffe's depthwise convolution implemented by group is very slow.
your profile has no DepthwiseConvolutionLayer

**Comment by shicai** [comment]
by setting #input_channels = #output_channels = #groups for a convolution layer in caffe, this conv layer is indeed a depthwise convolution layer.

**Comment by sunjunlishi** [comment]
thanks you

**Comment by zhaiyuqiang** [comment]
Hi, shicai
Did you update it to cudnn7?

**Comment by lcj820** [comment]
@NicolaiHarich hi, how do you solve this question?Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNA, thanks

**Comment by Ai-is-light** [comment]
good work. There are someone who can solve the long trian time. When I use the MobileNet to change the VGG16, I found that the CAFFE TIME of MobileNet was longer than the VGG's time. I'm really confused by this issue. @GragonShit @ @ @sudevbohra @cooliybob @shicai @

**Comment by shicai** [comment]
it has been discussed for a long time.
the implementation of depthwise conv in caffe is very slow.
you'd better implement it by yourself.

**Comment by ghost** [comment]
Hi @NicolaiHarich and @shicai ,

Just wondering if you guys have any update on experimenting depthwise-conv with CuDNN7 and if it runs successfully in @shicai's mobilenet-v1? 
I am currently using @yonghenglh6 depthwise-conv so I was wondering if CuDNN7 works and performs better. Any progress/update is very much appreciated, so we can continue from there. Thanks :)
