### ISSUE TITLE
About transform_param

### ISSUE THREAD

**Issue by ryusaeba** [shicai/MobileNet-Caffe#19]
Hi there, 
I would like to do detection. If I use your caffemodel as initial weight as my base network. 
It is better to add your transform parameters  (as below shows) in my .prototxt, right?
| #  transform_param {
| #    scale: 0.017
| #    mean_value: [103.94,116.78,123.68]
So your input data range is changed from [0-255] to [0-4.335]. My understanding is correct?

**Comment by shicai** [comment]
yes, use these tranform parameters.
the input range is changed from [0, 255] to [-2.x, 2.x], because you subtract the mean values of BGR.

**Comment by ryusaeba** [comment]
Thanks for the kindly reply :)
