### ISSUE TITLE
Input image preprocessing

### ISSUE THREAD

**Issue by zvadaszi** [shicai/MobileNet-Caffe#24]
Hi @shicai and thanks for porting this to Caffe!

I'm using this code https://github.com/BVLC/caffe/blob/master/examples/00-classification.ipynb for testing the model but get odd results. The closest I can get to an acceptable result is by commenting these lines:
#transformer.set_mean('data', (mu))            # subtract the dataset-mean value in each channel
#transformer.set_raw_scale('data', 255)      # rescale from [0, 1] to [0, 255]
I suppose it is something related to scale: 0.017 but I cannot figure out what to change.

How should the input be transformed in order to get good results? Thanks.

**Comment by shicai** [comment]
`transformer.set_input_scale('data', 0.017)`

**Comment by zvadaszi** [comment]
Thanks.

**Comment by jfuentescpp** [comment]
Hi @zvadaszi, I'm also trying to use that example code with this model. I'm getting nan ... :( can you point me in the right direction. Maybe share you final code as a gist ? 

Thanks in advance !

**Comment by zvadaszi** [comment]
@jfuentescpp in order to run I had to to two things:
1. uncomment all these lines in the deploy prototxt:  #    engine: CAFFE
2. add the scaling mentioned by shicai below _transformer.set_raw_scale_ like this:
```
transformer.set_raw_scale('data', 255)      # rescale from [0, 1] to [0, 255]
transformer.set_input_scale('data', 0.017)
```

**Comment by jfuentescpp** [comment]
@zvadaszi  thanks for helping! but I'm still stuck :( 

This is what I have don't so far:

1. uncomment # engine: CAFFE on `mobilenet_deploy.prototxt`
2. add the scaling mentioned by shicai below transformer.set_raw_scale like this:
 `transformer.set_input_scale('data', 0.017)`
3. set image size to 224x224 ` net.blobs['data'].reshape(1,  # batch size 3,           # 3-channel (BGR) images  224, 224)  # image size is 227x227`
4. `transformer.set_mean('data', np.array([103.94,116.78,123.68]))  # subtract the dataset-mean value in each channel`

the rest is the same, still when `net.forward()` `net.blobs['fc7'].data` is only `nan`

I also tried adding a softmax layer to the network but same result.  
`layer {
  name: "prob"
  type: "Softmax"
  bottom: "fc7"
  top: "prob"
}`

**Comment by jfuentescpp** [comment]
It seams problem was with the .caffemodel itself. Downloading it from `https://github.com/cdwat/MobileNet-Caffe.git` solved it.

Thanks
