### ISSUE TITLE
Scale layer after BatchNorm

### ISSUE THREAD

**Issue by chaosmail** [shicai/MobileNet-Caffe#35]
Hi @shicai 
could you explain the need/purpose of the Scale layer after every BatchNorm?
Thanks a lot!
Best, Christoph

**Comment by shicai** [comment]
BN can be formulated as y = gamma * ( (x - mean) / std) + beta.
In caffe, `BatchNorm` layer can only do mean-std normalization, so we need a `Scale` layer to learn linear transform parameters `gamma` and `beta`.

**Comment by alekhyadarsi** [comment]
Hi@shicai
could you explain me...
what are the values showing in the scale layer of mobile net v1.are they gamma or beta??
Thanks a lot!

**Comment by shicai** [comment]
yes, in that layer, scale is gamma, bias is beta.

**Comment by alekhyadarsi** [comment]
Thanks for your reply@shicai
 sorry i didnot get you.My question is the following
  conv1/bn has only 32 values,conv1/scale has only 32 values.what are those values??

**Comment by shicai** [comment]
as you know, y = gamma * (x - mean) /std + beta, conv1/bn saves mean and var values for each channel of conv1, and conv1/scale saves gamma and beta values.

**Comment by alekhyadarsi** [comment]
Thanks for your reply@shicai
ya kk understood.is there any fixed point model for mobile net v1

**Comment by alekhyadarsi** [comment]
hi@shicai
Do we need to padding for input 224 to get conv1 output??if so how much??
My output of conv1/scale is not matching with caffe output
