### ISSUE TITLE
what is the alpha value of the caffe-mobilenet

### ISSUE THREAD

**Issue by samsun639** [shicai/MobileNet-Caffe#36]
tensorflow-mobilenet has four alpha value,(1, 0.75, 0.5, 0.25)
https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md

what is the alpha value of the pretained caffe-mobilenet?

Thanks!

**Comment by samsun639** [comment]
From the top accuracy , I guess it is 1 .

thanks!

**Comment by shicai** [comment]
yes, it is 1.0
