### ISSUE TITLE
Can not load model weights

### ISSUE THREAD

**Issue by BalintMagyar4** [shicai/MobileNet-Caffe#40]
I'm using NVIDIA DIGITS for object detection and I want to use your MobileNet model as the inner model.
But when I load the weights from the caffe model I get the following error:

Check failed: target_blobs.size() == source_layer.blobs_size() (5 vs. 3) Incompatible number of blobs for layer conv1/bn

I get similar errors in every batchnorm layer.

Which Caffe model did you use?

**Comment by shicai** [comment]
official caffe from bvlc
