### ISSUE TITLE
how to change the two super-parameters ?

### ISSUE THREAD

**Issue by Ai-is-light** [shicai/MobileNet-Caffe#44]
how to change the two super-parameters ? Did anyone try it? @shicai

**Comment by shicai** [comment]
which parameters?

**Comment by Ai-is-light** [comment]
The width multiplier and resolution multiplier in the paper. we have to change them by hands? Thanks

**Comment by shicai** [comment]
yes, you can change it by hands.
or you can write your own scripts to generate prototxt files.
