### ISSUE TITLE
Simply running "classification" fails... whats wrong??

### ISSUE THREAD

**Issue by rmbarbosa** [shicai/MobileNet-Caffe#46]
Hi all,
i just used a simple command running the classification.exe tool that comes with caffe windows prebuilt binaries... 
i used an image of tabby the cat
https://devblogs.nvidia.com/wp-content/uploads/2016/07/cute.jpg
, the mean and labels from imagenet and
mobileNet-caffe prototxt and model file like this:

classification mobilenet_deploy.prototxt.txt mobilenet.caffemodel imagenet_mean.binaryproto labels.txt cute.jpg
---------- Prediction for cat.jpg ----------
10.9953 - "n02948072 candle, taper, wax light"
10.6561 - "n06874185 traffic light, traffic signal, stoplight"
9.6234 - "n04591713 wine bottle"
9.1139 - "n04286575 spotlight, spot"
9.0703 - "n04356056 sunglasses, dark glasses, shades"

now, even if i change the image, the results are allways the same...
what am i missing??
thank you..

**Comment by shicai** [comment]
we did not use `imagenet_mean.binaryproto` for image processing, and please make sure your `labels.txt` is the same as ours (see: https://github.com/shicai/MobileNet-Caffe/issues/5).

**Comment by rmbarbosa** [comment]
Thank you. But well, i must say that to put this repository code to work is like going fishing or worse... we have to read all the issues and take one thing from here another from there... why not just write on the initial readme a sample code for forward exec??.,.. nevertheless i created a simple py script and using the model, prototxt and labels that you recomended, and it still does not seem to work well because the results this script outputs are:
[[["'n02123159 tiger cat'"]]
 [["'n02119022 red fox, Vulpes vulpes'"]]
 [["'n02119789 kit fox, Vulpes macrotis'"]]
 [["'n02113023 Pembroke, Pembroke Welsh corgi'"]]
 [["'n02123045 tabby, tabby cat'"]]]

and tipically this would give on standard caffe image net:
---------- Prediction for cat.jpg ----------
0.3094 - "n02124075 Egyptian cat"
0.1761 - "n02123159 tiger cat"
0.1221 - "n02123045 tabby, tabby cat"
0.1132 - "n02119022 red fox, Vulpes vulpes"
0.0421 - "n02085620 Chihuahua"

-----here is the my python code----
```
import caffe
import numpy as np

caffe.set_mode_cpu()

model_def = 'mobilenet_deploy.prototxt'
model_weights = 'mobilenet.caffemodel'

net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

# create transformer for the input called 'data'
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})

transformer.set_transpose('data', (2,0,1))  # move image channels to outermost dimension
transformer.set_mean('data', np.array([103.94,116.78,123.68])) # subtract the dataset-mean value in each channel
transformer.set_raw_scale('data', 255)      # rescale from [0, 1] to [0, 255]
transformer.set_input_scale('data', 0.017)
transformer.set_channel_swap('data', (2,1,0))  # swap channels from RGB to BGR

# set the size of the input (we can skip this if we're happy
#  with the default; we can also change it later, e.g., for different batch sizes)
net.blobs['data'].reshape(1,         # batch size
                          3,         # 3-channel (BGR) images
                          224, 224)  # image size is 227x227
						  
image = caffe.io.load_image('F:\digits_data\mobilenet\MobileNet-Caffe-master\cat.jpg')
transformed_image = transformer.preprocess('data', image)

# copy the image data into the memory allocated for the net
net.blobs['data'].data[...] = transformed_image

### perform classification
output = net.forward()

output_prob = output['prob'][0]  # the output probability vector for the first image in the batch

print 'predicted class is:', output_prob.argmax()

# load ImageNet labels
labels_file = 'labels.txt'    
labels = np.loadtxt(labels_file, str, delimiter='\t')

print 'output label:', labels[output_prob.argmax()]

# sort top five predictions from softmax output
top_inds = np.argsort(output_prob,0)[::-1][:5]  # reverse sort and take five largest items

print 'labels:'
print labels[top_inds]
```
----------------------------
So good people, any thoughts or directions on whats wrong here??

**Comment by rmbarbosa** [comment]
just for reference on my previous post, regarding the output extraction on the previous script, i added an aditional layer to the end of prototxt 
`layer { name: "prob" type: "Softmax" bottom: "fc7" top: "prob" }`

**Comment by shicai** [comment]
@rmbarbosa  updated, please see `readme`.

**Comment by rmbarbosa** [comment]
@shicai thank you very much for the update... it is really very important to see how this works in a clear way. And now its clear as water... ;-)
Again, congratulations on the work of mobilenet caffe.
Fantastic job.
