### ISSUE TITLE
problem in conv4_7 layer

### ISSUE THREAD

**Issue by linchaozhang** [shicai/MobileNet-Caffe#50]
for mobilenet _v2, stride=1 for conv4_7 in paper

**Comment by shicai** [comment]
there may be some typos in Table 2 in the paper, so it is not clear when to use stride=2. if you take a look at colomn 1, spatial size is reduced from 28 to 14, so there should be stride=2 used here.

**Comment by linchaozhang** [comment]
@shicai got it, there may be some typos in Table 2, you use stride = 1 in conv4_3，you take input_size as a standard, thank you！

**Comment by linchaozhang** [comment]
@shicai got it, there may be some typos in Table 2, you take input_size as a standard, use stride = 1 in conv4_3, thank you！

**Comment by wujiyang** [comment]
@linchaozhang  @shicai  there is a little difference in Table 2 between the arXiv paper v1 and the latest v3.  In paper v3,  it should be stride=1 for conv4_7 and stride=2 for conv4_3.

**Comment by wujiyang** [comment]
@shicai  I have a doubt about the layer structure. In the prototxt, conv2_2 and conv3_1 are actually in a group ,and  conv3_2、conv4_1、conv4_2 are of a same group, why split them into different numbers?
Is there any tricks here？ just curious about it.

**Comment by leochli** [comment]
Hi,
@wujiyang Thanks for pointing out the differences!
@shicai The paper says "The first layer of each sequence has a stride s and all others use stride 1." Yet it seems that you are doing down sampling at the end of each phase. Could you explain for that?

**Comment by shicai** [comment]
they share the same architecture, but are named in different ways. @leochli
