### ISSUE TITLE
Where is depthwise convolution layer?

### ISSUE THREAD

**Issue by 408550969** [shicai/MobileNet-Caffe#60]
Why some people add the DW layer to implement depthwise convolution on mobilenet,but it doesn't exist in your mobilenet v2 deploy.prototxt?
Thanks!

**Comment by zoufangyu1987** [comment]
I have the same promble.

**Comment by shicai** [comment]
I can only release pretrained models with standard official caffe. If you can not train, you'd better check the implementations or ask authors of those codes.

**Comment by 408550969** [comment]
Thanks!

**Comment by zoufangyu1987** [comment]
thank you!
