### ISSUE TITLE
Wrong strides in MobilenetV2

### ISSUE THREAD

**Issue by mathmanu** [shicai/MobileNet-Caffe#67]
The strides used for MobilenetV2 seems to be different from that in the MobileNetV2 descriped in the paper : https://arxiv.org/pdf/1801.04381.pdf

Expected strides (as in the paper).........: [2, 1, 2, 2, 2, 1, 2, 1, 1]
Strides used in this repo...........................: [2, 1, 2, 2, 1, 2, 2, 1, 1]

Because of this, the MAdds (Multiply Adds) of the MobileNetV2 is higher compared to that of the paper.

**Comment by shicai** [comment]
we followed the table in the first version of the paper. (there are typos.)
they fixed the typos in the second version.

**Comment by mathmanu** [comment]
It will be good to highlight this difference in the Readme of this repository. It may help other's like me who had a hard time spotting the exact difference with that described in the paper.

Thanks for this work.
