### ISSUE TITLE
traning time

### ISSUE THREAD

**Issue by yunren** [shicai/MobileNet-Caffe#8]
Hi. when I train fast rcnn with the MobileNet, I have found that the traning time is very long. 
It takes 90sec every 20 iteration while  the ResNet only takes 17sec.
Is it normal? 

how to speed up?

my gpu is gtx1080

**Comment by shicai** [comment]
training mobilenet with caffe is very slow, perhaps as slow as training resnet with 80-100 layers.
you can implement channel-wise conv by yourself for speedup.

**Comment by yunren** [comment]
thanks for your answer
